# Generated by Django 3.0.7 on 2020-06-27 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='bio',
            field=models.TextField(default='Go to settings to update', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='ig_link',
            field=models.CharField(default='Go to setting to update', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.TextField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
