# Generated by Django 3.0.7 on 2020-06-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200627_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
