# Generated by Django 3.0.7 on 2020-06-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200628_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
