# Generated by Django 3.0.7 on 2020-06-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire',
            old_name='business',
            new_name='hired_by',
        ),
        migrations.RenameField(
            model_name='hire',
            old_name='influencer',
            new_name='hired_influencer',
        ),
    ]
