# Generated by Django 3.0.7 on 2020-07-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200630_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
